// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authors

import (
	"database/sql"
)

type Author struct {
	ID        int64
	Name      string
	Bio       sql.NullString
	BirthDate sql.NullTime
}

type Bio struct {
	ID   int64
	Text string
}
