// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http).

package authors

import (
	"github.com/jackc/pgx/v5/pgxpool"
)

// NewService is a constructor of a interface { func RegisterHandlers(*http.ServeMux) } implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier Querier, db *pgxpool.Pool) *Service {
	return &Service{querier: querier, db: db}
}
