// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http).

package authors

import "net/http"

func (s *Service) RegisterHandlers(mux *http.ServeMux) {
	mux.HandleFunc("POST /authors", s.handleCreateAuthor())
	mux.HandleFunc("DELETE /authors/{id}", s.handleDeleteAuthor())
	mux.HandleFunc("GET /authors/{id}", s.handleGetAuthor())
	mux.HandleFunc("GET /authors", s.handleListAuthors())
	mux.HandleFunc("PUT /authors/{id}", s.handleUpdateAuthor())
	mux.HandleFunc("PATCH /authors/{id}/bio", s.handleUpdateAuthorBio())
}
