// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http).

package authors

import "net/http"

func (s *Service) RegisterHandlers(mux *http.ServeMux) {
	mux.HandleFunc("POST /authors/author", s.handleCreateAuthor())
	mux.HandleFunc("DELETE /authors/author/{id}", s.handleDeleteAuthor())
	mux.HandleFunc("GET /authors/author/{id}", s.handleGetAuthor())
	mux.HandleFunc("GET /authors/authors", s.handleListAuthors())
}
