version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"    
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - GODEBUG=httpmuxgo121=0

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
