// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http). DO NOT EDIT.

package main

import (
	"net/http"

	"github.com/jackc/pgx/v5/pgxpool"

	authors_app "authors/internal/authors"
)

func registerHandlers(mux *http.ServeMux, db *pgxpool.Pool) {
	authorsService := authors_app.NewService(authors_app.New(), db)
	authorsService.RegisterHandlers(mux)
}
